server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  application:
    name: USER-SERVICE
  config:
    import: configserver:http://localhost:8085

